if (MSVC)
  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /EHa")
  set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /EHa")

  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}  /MDd")
  set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG}  /MDd")

  set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}  /MD")
  set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE}  /MD")
endif()

add_definitions("-DUDT_EXPORTS -wd4996 -wd4290 -DXML_LIBRARY -DXERCES_USE_MSGLOADER_INMEMORY -DXERCES_STATIC_LIBRARY -DNO_DEBUG_NEW -DVC_EXTRALEAN -DSTRSAFE_NO_DEPRECATE -DBOOST_USE_WINDOWS_H  -DBOOST_ENABLE_ASSERT_HANDLER -DWIN32 -D_WINDOWS -D_USRDLL -D_WIN32_WINNT=0x0600 -D_AFXDLL")
add_definitions("-DWIN32_LEAN_AND_MEAN")
